const SENTENCE_BANK = {
    easy: [
        "I like to practice typing every day.",
        "Typing is a useful computer skill.",
        "This is a simple sentence for beginners.",
        "I am learning to type faster.",
        "Practice helps improve your speed.",
        "I enjoy learning new skills online.",
        "The cat is sitting on the chair.",
        "We are using a keyboard to type.",
        "He reads a book every evening.",
        "She goes to school by bus.",
        "I wake up early in the morning.",
        "Typing games are fun and helpful.",
        "The sun rises in the east.",
        "Water is important for life.",
        "I drink water every day.",
        "The sky is very blue today.",
        "My computer is on the desk.",
        "I love listening to music.",
        "He plays football with friends.",
        "She writes in her notebook."
    ],

    medium: [
        "JavaScript is widely used for building interactive websites.",
        "Frontend development focuses on user interface design.",
        "Backend systems handle server logic and databases.",
        "Consistent practice improves typing speed and accuracy.",
        "Developers build applications using different frameworks.",
        "Typing efficiently requires focus and daily practice.",
        "Modern web applications use APIs for communication.",
        "Databases store and manage large amounts of data.",
        "Programming requires logic and problem solving skills.",
        "Software development involves planning and testing.",
        "Cloud computing allows scalable application hosting.",
        "Web development includes frontend and backend systems.",
        "Debugging helps find and fix errors in code.",
        "Good developers write clean and maintainable code.",
        "React is a popular JavaScript library for UI.",
        "Node.js allows JavaScript to run on the server.",
        "APIs connect different software systems together.",
        "Authentication protects user accounts and data.",
        "Version control helps track changes in code.",
        "Learning to code takes patience and consistency."
    ],

    hard: [
        "Asynchronous programming allows multiple tasks to execute without blocking execution flow.",
        "Microservices architecture improves scalability by dividing applications into independent services.",
        "Authentication and authorization are essential for securing modern web applications.",
        "Optimization techniques significantly improve application performance and efficiency.",
        "Full stack development includes both frontend interfaces and backend systems.",
        "Multithreading enables concurrent execution of multiple processes in a program.",
        "Database normalization reduces redundancy and improves data integrity.",
        "Cloud infrastructure provides scalable computing resources on demand.",
        "Software engineering requires systematic design and implementation approaches.",
        "Distributed systems consist of multiple interconnected nodes working together.",
        "API endpoints allow communication between client and server applications.",
        "Cybersecurity focuses on protecting systems from unauthorized access.",
        "Machine learning algorithms improve automatically through experience and data.",
        "Big data analytics processes large datasets to extract meaningful insights.",
        "System design involves planning scalable and efficient architectures.",
        "Performance optimization reduces latency and improves user experience.",
        "Containerization helps deploy applications consistently across environments.",
        "DevOps practices combine development and operations for faster delivery.",
        "Concurrency control ensures safe execution of multiple processes.",
        "Scalable systems can handle increasing loads without performance loss."
    ]
};